export const SET_USER_DATA = 'SET_USER_DATA';
export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
