export const BIKE_UNLOCKED = 'BIKE_UNLOCKED';
export const BIKE_UNLOCK_FAILED = 'BIKE_UNLOCK_FAILED';
export const BIKE_LOCKED = 'BIKE_LOCKED';
export const BIKE_LOCK_FAILED = 'BIKE_LOCK_FAILED';
export const CONNECTED_TO_SOCKET = 'CONNECTED_TO_SOCKET';
export const LOCK_CONNECTION_CLOSED = 'LOCK_CONNECTION_CLOSED';
export const BIKE_LOCK_LOCKING = 'BIKE_LOCK_LOCKING';
export const BIKE_LOCK_UNLOCKING = 'BIKE_LOCK_UNLOCKING';
