notifications:
  email: false

jobs:
  include:
    - stage: test
      if: tag IS present OR branch = master OR type IN (pull_request) 
      language: node_js
      node_js: 9
      cache: yarn
      install: yarn install
      script: yarn run ci
      deploy:
        provider: script
        skip_cleanup: true
        script: bash .travis/exp-publish.sh
        on:
          tags: true

      
