notifications:
  email: false

jobs:
  include:
    - stage: test
      if: tag IS present OR branch = master OR type IN (pull_request) 
      language: node_js
      node_js: node
      cache: yarn
      before_install: ./.travis/add-ssh-key.sh
      install: yarn install
      script: yarn run ci
      deploy:
        provider: script
        skip_cleanup: true
        before_script: exp login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        script: exp publish
        on:
          tags: true

    - stage: build
      if: sender = rit-bikeshare-travis AND tag IS present AND env(TRAVIS_SECURE_ENV_VARS) = true
      language: android
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - ./.travis/add-ssh-key.sh
        - ./.travis/exp-detach.sh
        - mv secret_files/test-keystore.jks android/test-keystore.jks
        - mv secret_files/keystore.properties android/keystore.properties
        - cd android
      script: "./gradlew clean build"
      android:
        components:
          - tools
          - platform-tools
          - tools
          - android-27
          - build-tools-27.0.1
          - extra-android-support
          - extra-android-m2repository
          - extra-google-m2repository

    - stage: build
      if: sender = rit-bikeshare-travis AND tag IS present AND env(TRAVIS_SECURE_ENV_VARS) = true
      language: objective-c
      before_install:
        - ./.travis/add-ssh-key.sh
        - ./.travis/exp-detach.sh
        - cd ios
      xcode_project: MyNewProject.xcodeproj # path to your xcodeproj folder
      xcode_scheme: MyNewProjectTests

      
