export const FETCH_CURRENT_RENTAL = 'FETCH_CURRENT_RENTAL';
export const FETCH_CURRENT_RENTAL_SUCCESS = 'FETCH_CURRENT_RENTAL_SUCCESS';
export const FETCH_CURRENT_RENTAL_FAILED = 'FETCH_CURRENT_RENTAL_FAILED';
