export const DAMAGE_LOOKUP_SUCCESS = 'DAMAGE_LOOKUP_SUCCESS';
export const DAMAGE_LOOKUP_ERROR = 'DAMAGE_LOOKUP_ERROR';
export const DAMAGE_LOOKUP = 'DAMAGE_LOOKUP';
export const CLEAR_DAMAGE_LOOKUP_STATUS = 'CLEAR_DAMAGE_LOOKUP_STATUS';
export const FETCH_DAMAGED_BIKES_SUCCESS = 'FETCH_DAMAGED_BIKES_SUCCESS';
