export const BIKE_CHECKIN = 'BIKE_CHECKIN';
export const BIKE_CHECKIN_SUCCESS = 'BIKE_CHECKIN_SUCCESS';
export const BIKE_CHECKIN_FAILED = 'BIKE_CHECKIN_FAILED';
export const CLEAR_BIKE_CHECKIN_STATUS = 'CLEAR_BIKE_CHECKIN_STATUS';
