export const BIKE_CHECKOUT = 'BIKE_CHECKOUT';
export const BIKE_CHECKOUT_SUCCESS = 'BIKE_CHECKOUT_SUCCESS';
export const BIKE_CHECKOUT_FAILED = 'BIKE_CHECKOUT_FAILED';
export const CLEAR_BIKE_CHECKOUT_STATUS = 'CLEAR_BIKE_CHECKOUT_STATUS';
