export const DAMAGE_REPORT = 'DAMAGE_REPORT';
export const DAMAGE_REPORT_SUCCESS = 'DAMAGE_REPORT_SUCCESS';
export const DAMAGE_REPORT_FAILED = 'DAMAGE_REPORT_FAILED';
export const DAMAGE_REPORT_RESET = 'DAMAGE_REPORT_RESET';

export const FETCH_DAMAGE_TYPES = 'FETCH_DAMAGE_TYPES';
export const FETCH_DAMAGE_TYPES_SUCCESS = 'FETCH_DAMAGE_TYPES_SUCCESS';
export const FETCH_DAMAGE_TYPES_FAILED = 'FETCH_DAMAGE_TYPES_FAILED';
